app = "bot-crm-reporter-2"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services.ports]]
  port = 80
  handlers = ["http"]
[[services.ports]]
  port = 443
  handlers = ["tls","http"]

[[checks]]
  name = "httpchk"
  type = "http"
  port = 8080
  interval = "10s"
  timeout = "2s"
  method = "GET"
  path = "/healthz"
